### ISSUE TITLE
run tests from command line?

### ISSUE THREAD

**Issue by letmaik** [curran/jspm-mocha-example#1]
From your index.html I assume you had trouble making it run from the command line, right? Is this impossible? What is missing to make that work so that running `mocha` would be enough?

**Comment by letmaik** [comment]
I just found the [related discussion](https://github.com/jspm/jspm-cli/issues/843#issuecomment-115227637) in the jspm-cli project. I will try if and how well the suggested [approach](https://github.com/sroucheray/event-class/tree/master/test) works and report back. I hope I can skip the dummy `es6-test-setup.js` file and directly import the module to be tested in the tests, so something like...

``` js
var System = require("jspm");
var assert = require("assert");

System.import("src/moduletotest").then(function(mod) {
  describe("mod methods", function() {
    describe("#...", function() {
      //...
    }
  }    
})
.catch(function(e) {
    describe("JSPM", function() {
        it("should load the ES6 module", function(done) {
            assert.fail(null, "", e);
        })
    })
})
```

I have a feeling though that the `describe`s must be at the root to work properly, but I really would hate to have this promise boilerplate in each testcase...
EDIT: Yes, that doesn't work when the `describe`s are inside. Have to find another solution.
EDIT2: See work-around below.

**Comment by curran** [comment]
Yes, it's true that I had trouble getting Mocha to run on the command line with JSPM. This was one of the major things that stopped me from adopting JSPM. I would like to re-investigate soon though, I know there has been lots of work done on JSPM in the past few months.

I would love to hear about any technique that works for you if you do find a solution. There should be some straightforward path to write tests for ES6 code in ES6, and run them in the command line with Mocha, I just haven't seen it work yet.

**Comment by screendriver** [comment]
Same issue here. I want to write my code **and** test code in ES6.

**Comment by letmaik** [comment]
I found a funny work-around to at least run the tests and not have ridiculous boilerplate inside each test or additional setup files:

``` js
var System = require("jspm");
var assert = require("assert");

// boiler-plate
var count = 12 // numbers of tests in this module
it("ignoreme", function(done) {
    var iv = setInterval(function() {
      if (count === 0) {clearInterval(iv); done()}
    }, 500)
})
var oldit = it
it = function(name, fn) {count--; oldit(name, fn)}

// your tests
System.import("src/reader").then(function(reader) {
  describe("reader methods", function() {
    describe("#read", function() {
      it("should do stuff", function() {
        // test code
      })
    })
  })
})
```

The problem was that the file ran through without the tests having had enough time to actually start and letting mocha now about them. So, what the above does is start a waiting-test which waits until all tests have started and then succeeds itself. Obviously, this is rubbish, but it works! @guybedford Any idea how to make this nicer?

**Comment by curran** [comment]
Nice! Thank you for sharing this solution.

**Comment by screendriver** [comment]
I believe I've got it! :tada: Not only I can run my tests at the command line, I can mock dependencies as well.
See my pull request #2

**Comment by curran** [comment]
Great work! Merged.

**Comment by letmaik** [comment]
@ScreenDriver Looks good, I wonder if you can like I did require jspm and then skip requireing the config file. That should work right? Would make it even more easier.

**Comment by screendriver** [comment]
@neothemachine I've tried it but it does not work. I mean it does work in the first place but when you want to mock something it throws a `Cannot set property 'the-library' of undefined`.
[Here](https://gist.github.com/ScreenDriver/4245c2015d765f550982) is an example Gist where I mock the [bluebird](https://github.com/petkaantonov/bluebird) library. Yes I know, bluebird does not need to be mocked. It's only for this example and works only when you import `config.js`.

The most important part was to change the `baseUrl` in `config.js` from `baseURL: "/"` to `baseURL: "./"`. Without that it's not working.

Oh and by the way: because you import `systemjs` and `config.js` in your unit test file the tests are not working in the browser anymore.

**Comment by ScreenDriver** [comment]
Maybe someone can help me with this one systemjs/systemjs#725

**Comment by letmaik** [comment]
@ScreenDriver  I just tested this myself (using jspm import since I don't need mocks yet), and I simplified the `before` hook a bit more and made error handling better:

``` js
  before(() => {
    return System.import('./lib/myModule.js')
      .then(mod => myModule = mod)
  });
```

When import fails, then by returning the promise Mocha will automatically handle it correctly and display the error.  Feel free to put that in a pull request, I'm currently a little busy myself!

**Comment by letmaik** [comment]
By the way, when the test file has a syntax error, then the output gets really ugly now due to babel compilation (at least for me, under Windows console), I think this is because babel is not using console colors properly or they get messed up at some step when pushing the error around. Still, it's certainly very nice to write ES6 tests now! Good job.

**Comment by letmaik** [comment]
Sorry for spamming, just a suggestion for adding this to package.json:

``` js
  "scripts": {
    "test": "./node_modules/.bin/mocha --compilers js:babel/register test/tests"
  }
```

Then you can just do `npm test` and be happy.

**Comment by screendriver** [comment]
:+1: 

I added your suggestions to my already existent #3

**Comment by letmaik** [comment]
For another library of mine I needed real browser-based testing, and for that I use karma with karma-jspm and this has full jspm integration, so jspm import is happening from the start without any special things to do: https://github.com/Reading-eScience-Centre/leaflet-coverage/blob/master/test/util/utils.spec.js
I think this is how it should be, and I wonder if this can be achieved with the test-in-node approach that we are discussing here. I have a feeling that this could be solved by using/developing a different compiler for mocha for example, which more directly integrates jspm instead of just running babel. Because if you achieve that, then you can use the same test code base for node testing and browser testing, which.... would be wonderful. EDIT: well, more or less... of course node  would miss many browser features, for example "document.", XMLHttpRequest, ... but still, for some libraries which are pretty basic (number crunching or whatever) it might be suitable

**Comment by curran** [comment]
Nice work adding a mock example and `npm test` script. Merged the PR. I'm considering trying to set up a travis integration to see if all this plays well with CI.

**Comment by curran** [comment]
Travis works! I think we've got this issue sorted out now - all the code is ES6 and we can run tests with Mocha. After these changes this repo is much more usable as a starter project / learning resource. Thank you both for your work on this.

Closing the issue, but feel free to continue the conversation here.
